# SPDX-FileCopyrightText: Opinsys Oy <dev@opinsys.fi>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1
SPDX-PackageName = "External Portal"
SPDX-PackageSupplier = "Opinsys Oy <dev@opinsys.fi>"
SPDX-PackageDownloadLocation = "https://github.com/puavo-org/externalportal"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Opinsys Oy and contributors <dev@opinsys.fi>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["l10n/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Nextcloud translators <https://www.transifex.com/nextcloud/>"
SPDX-License-Identifier = "AGPL-3.0-or-later"
